App\Entity\UserManagement\User:
    attributes:
        id:
            groups: ['tablature:read']
        username:
            groups: ['tablature:read']
        info:
            groups: ['tablature:read']

App\Entity\UserManagement\UserInfo:
    attributes:
        id:
            groups: ['tablature:read']
        firstName:
            groups: ['tablature:read']
        lastName:
            groups: ['tablature:read']
            